### ISSUE TITLE
bevy_ecs regression

### ISSUE THREAD

**Issue by compiler-errors** [rust-lang/trait-system-refactor-initiative#175]
Not yet minimized

https://crater-reports.s3.amazonaws.com/pr-133502-1/try%23fa8e241660363f48d64b66b05eea58c93ab828fb/reg/bevy_app-0.16.0-rc.3/log.txt

```
[INFO] [stdout] error[E0283]: type annotations needed: cannot satisfy `MaybeLocation: FromReflect`
[INFO] [stdout]     --> /opt/rustwide/cargo-home/registry/src/index.crates.io-1949cf8c6b5b557f/bevy_ecs-0.16.0-rc.3/src/event/base.rs:118:12
[INFO] [stdout]      |
[INFO] [stdout] 118  | pub struct EventId<E: Event> {
[INFO] [stdout]      |            ^^^^^^^^^^^^^^^^^
[INFO] [stdout]      |
[INFO] [stdout] note: multiple `impl`s or `where` clauses satisfying `MaybeLocation: FromReflect` found
[INFO] [stdout]     --> /opt/rustwide/cargo-home/registry/src/index.crates.io-1949cf8c6b5b557f/bevy_ecs-0.16.0-rc.3/src/change_detection.rs:1197:45
[INFO] [stdout]      |
[INFO] [stdout] 1197 | #[cfg_attr(feature = "bevy_reflect", derive(Reflect))]
[INFO] [stdout]      |                                             ^^^^^^^
[INFO] [stdout]      |
[INFO] [stdout]     ::: /opt/rustwide/cargo-home/registry/src/index.crates.io-1949cf8c6b5b557f/bevy_ecs-0.16.0-rc.3/src/event/base.rs:115:12
[INFO] [stdout]      |
[INFO] [stdout] 115  |     derive(Reflect),
[INFO] [stdout]      |            ^^^^^^^
[INFO] [stdout] note: required for `EventId<E>` to implement `GetTypeRegistration`
[INFO] [stdout]     --> /opt/rustwide/cargo-home/registry/src/index.crates.io-1949cf8c6b5b557f/bevy_ecs-0.16.0-rc.3/src/event/base.rs:115:12
[INFO] [stdout]      |
[INFO] [stdout] 115  |     derive(Reflect),
[INFO] [stdout]      |            ^^^^^^^ unsatisfied trait bound introduced in this `derive` macro
[INFO] [stdout] ...
[INFO] [stdout] 118  | pub struct EventId<E: Event> {
[INFO] [stdout]      |            ^^^^^^^^^^^^^^^^^
[INFO] [stdout]      = note: this error originates in the derive macro `Reflect` (in Nightly builds, run with -Z macro-backtrace for more info)
```

Tons of ambiguities when building `bevy_ecs`.

**Comment by lcnr** [comment]
caused by not preferring where-bounds over alias bounds for projection goals: https://github.com/rust-lang/rust/blob/5961e5ba3daa20d98f549eb9029105ae50c13aed/compiler/rustc_next_trait_solver/src/solve/assembly/mod.rs#L803-L826

we've got `Iterator<Item = ()>` where-bound and `Iterator<Item = Self::Assoc>` alias-bound

have to eat lunch, but the fix for that issue is easy :3

**Comment by lcnr** [comment]
> "type annotations needed: cannot satisfy `MaybeLocation: FromReflect`"

caused by https://github.com/rust-lang/rust/pull/139791 afaict. The only remaining issue are 2 variants of this one (and once for each tuple size)

```
error[E0283]: type annotations needed
   --> crates/bevy_ecs/src/system/exclusive_function_system.rs:295:17
    |
295 |                 call_inner(self, input, world, $($param),*)
    |                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ cannot infer type
...
302 | all_tuples!(impl_exclusive_system_function, 0, 16, F);
    | ----------------------------------------------------- in this macro invocation
    |
    = note: cannot satisfy `_: input::SystemInput`
    = help: the following types implement trait `input::SystemInput`:
```

**Comment by lcnr** [comment]
the last regressions are intended
```rust
        impl<In, Out, Func, $($param: SystemParam),*> SystemParamFunction<(HasSystemInput, fn(In, $($param,)*) -> Out)> for Func
        where
            Func: Send + Sync + 'static,
            for <'a> &'a mut Func:
                FnMut(In, $($param),*) -> Out +
                FnMut(In::Param<'_>, $(SystemParamItem<$param>),*) -> Out,
            In: SystemInput + 'static,
            Out: 'static
        {
            type In = In;
            type Out = Out;
            type Param = ($($param,)*);
            #[inline]
            fn run(&mut self, input: In::Inner<'_>, param_value: SystemParamItem< ($($param,)*)>) -> Out {
                fn call_inner<In: SystemInput, Out, $($param,)*>(
                    mut f: impl FnMut(In::Param<'_>, $($param,)*)->Out,
                    input: In,
                    $($param: $param,)*
                )->Out{
                    f(input, $($param,)*)
                }
                let ($($param,)*) = param_value;
                call_inner(self, In::wrap(input), $($param),*)
            }
        }
```
the call to `call_inner` does not constrain `In`. This previously compiled as we incorrectly relate arguments of higher ranked aliases in the old solver.
